### ISSUE TITLE
bug in actionbars setting up.

### ISSUE THREAD

**Issue by CadenceArmor** [cogwerkz/gUI4#16]
Message: Interface\AddOns\gUI4_ActionBars\gUI4_ActionBars.lua:87: attempt to index field 'actionName' (a nil value)
Time: 08/10/17 19:54:40
Count: 1
Stack: Interface\AddOns\gUI4_ActionBars\gUI4_ActionBars.lua:87: attempt to index field 'actionName' (a nil value)Interface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: ?
Interface\AddOns\gUI4_ActionBars\gUI4_ActionBars.lua:87: in function <Interface\AddOns\gUI4_ActionBars\gUI4_ActionBars.lua:84>
Interface\AddOns\gUI4_ActionBars\gUI4_ActionBars.lua:137: in function ?'
Interface\FrameXML\ChatFrame.lua:4486: in functionChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4154: in function ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4190: in functionChatEdit_OnEnterPressed'
[string ":OnEnterPressed"]:1: in function <[string ":OnEnterPressed"]:1>

Locals: errorMessage = "Interface\AddOns\gUI4_ActionBars\gUI4_ActionBars.lua:87: attempt to index field 'actionName' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0

:frowning: just happened with and without bagnon, BT, and the masque stuff on and off
occurs with the following commands being used....

/showbinds 
/hidebinds 
/shownames 
/hidenames

the only things on when confirming the error

goldpaw:sharedmedia
gUI core
gUI actionbars

**Comment by goldpaw** [comment]
Fixed in 1.1.26-Release! :)
