### ISSUE TITLE
Fishing Button appears at /reload or login until we gain/lose a buff, even with no fishing pole equipped!

### ISSUE THREAD

**Issue by CadenceArmor** [cogwerkz/gUI4#18]
everytime I refresh my UI as I'm checking and laying out the pieces the fishing button pops up.....

this is regardless of which option I click.

it goes away then i refresh and it comes back....but its not every refresh oddly enough.

![fishbug](https://user-images.githubusercontent.com/30738949/29227288-f31cae26-7e9a-11e7-9e98-1a3caa827ac3.png)

 changeing from this ^^setting, i get VV after the setting change from ^^to VV (2 refreshes between setting changes). one registers the ^^ to vv setting change from the show to the unshow but second refresh i get vv having the setting change from ^^ to vv.

![fishbug2](https://user-images.githubusercontent.com/30738949/29227453-7f2301cc-7e9b-11e7-8c69-88a89edd52a9.png)

weirdness.....

if you have a question say so and ill try to do a pictoral illistration better so you can find it or help me with the finding it wrong.

**Comment by goldpaw** [comment]
Yeah, I'm aware of that issue. The instant you gain a buff of some sort, it disappears. 

It's on my todo list :)

**Comment by goldpaw** [comment]
Should be fixed in 1.1.30-Release.
