### ISSUE TITLE
buggy time:(

### ISSUE THREAD

**Issue by CadenceArmor** [cogwerkz/gUI4#19]
![military time](https://user-images.githubusercontent.com/30738949/29424579-ea3df76a-8345-11e7-85d3-e422346946b1.png)

idk what to call the clock issue......

no matter which setting other than with military time format selected...as you can see..... the times match...... im assuming the later matches because i'm in the realm time area for the NA servers.....i am in central timezone.

whats it doing that its not adjusting the am/pm formatting stuff without it being military time optioned.....i know military time but would rather not try to remember and calculate to the appropriate time LOL.

**Comment by goldpaw** [comment]
hm. probably a result of me being Norwegian. We don't have that AM/PM thing, all our clocks are in the 24 hour format as we can count to 24 here.... *grins wickedly* 

I'll get that fixed. Totally not the intention to make you think you'd lost 12 hours, lol! :D
