### ISSUE TITLE
Bug with moving on actionbars

### ISSUE THREAD

**Issue by Anderzenn** [cogwerkz/gUI4#35]
When I try and move a spell in my actionbars it uses it. I can move it but it uses the spell.

This issue is also present in Diabolic UI.

**Comment by noixdecitron** [comment]
same problem :( Did you find a solution ?

**Comment by goldpaw** [comment]
It's not an issue, it's not a bug. The bars in both UIs simply follow the Blizzard setting for this. 

This is a Blizzard setting which used to be available through the interface options, but in Legion was removed. You can change this setting manually with the below scripts, or with the addon AdvancedInterfaceOptions lined below:

Cast on key release: 
/run SetCVar("ActionButtonUseKeyDown", 0); ReloadUI()

Cast on key down:
/run SetCVar("ActionButtonUseKeyDown", 1); ReloadUI()

AdvancedInterfaceOptions addon:
https://mods.curse.com/addons/wow/advancedinterfaceoptions
