### ISSUE TITLE
Interfering with WeakAura

### ISSUE THREAD

**Issue by ChandlerXia** [cogwerkz/gUI4#38]
For some reason WeakAura 2 is bugging out when GUI is loaded now. It happens when ever I click a button in WeakAura.

Error report:

54x ...Ace3\AceGUI-3.0-34\widgets\AceGUIContainer-TabGroup.lua:66: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: ?
...Ace3\AceGUI-3.0-34\widgets\AceGUIContainer-TabGroup.lua:66: in function <...Ace3\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:64>

Locals:
(*temporary) = "igCharacterInfoTab"

**Comment by goldpaw** [comment]
This is most likely not gUI. This is a PlaySound error in Ace3. Goldpaw's UI does not use Ace3, nor does it have any of the PlaySound errors introduced in wow patch 7.3.0. Either WeakAuras is outdated, or something else is replacing your Ace3 with an outdated version. That's my guess. 

Try installing the Ace3 standalone. That should in theory overwrite the other faulty Ace3 version that fires the error: 
https://www.curseforge.com/wow/addons/ace3
 
Remember to completely exit the game when installing or updating addons, as wow can't discover new files when it's running.

**Comment by ChandlerXia** [comment]
Thanks for the quick reply! That fixed the problem.
