### ISSUE TITLE
LUA Error while trying different /gui options

### ISSUE THREAD

**Issue by Nimboi** [cogwerkz/gUI4#41]
Hi. 

Whatever i try to do. If I go to positioning and press Toggle Lock or do something else in the options window I always get the same error message: 

"Message: ...P_Ace3\GP_AceGUI-3.0\widgets\AceGUIWidget-Button.lua:21: attempt to call global 'PlaySoundKitID' (a nil value)
Time: 12/19/17 20:08:36
Count: 1
Stack: ...P_Ace3\GP_AceGUI-3.0\widgets\AceGUIWidget-Button.lua:21: attempt to call global 'PlaySoundKitID' (a nil value)
[C]: in function `PlaySoundKitID'
...P_Ace3\GP_AceGUI-3.0\widgets\AceGUIWidget-Button.lua:21: in function <...P_Ace3\GP_AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

Locals: " 

I Just downloaded the addon. And I have also tried disabling every other addon, using only gUI but it still gives me this message. Any ideas?

**Comment by goldpaw** [comment]
Totally my bad. Forgot a line of text in today's 1.1.33 update. Fixed it in 1.1.34, which is already live on GitHub and should be available on Curse/Twitch in anything from a few minutes to a few hours after writing this.

**Comment by Nimboi** [comment]
Ah no worries. 
From what I have seen so far, the UI looks good and is something I can se myself using! 

Keep up the good work!
