### ISSUE TITLE
Voice error sounds

### ISSUE THREAD

**Issue by Batchman85** [cogwerkz/gUI4#48]
Can you please add option to re-enable these sounds?

(out of mana, no target, etc. un/intentionally removed by objectives module)

**Comment by goldpaw** [comment]
This UI doesn't change those settings, haven't ever removed them, and they have nothing to do with the UI at all. 

Any sound fx settings are located in the sound settings from the game's system menu, and can be changed there. Blizzard might have removed some of the error sounds in 7.3.5 from the game, but that's nothing we can do anything about.
